version: "3.9"
services:
    swag:
        image: ghcr.io/linuxserver/swag
        container_name: swag
        cap_add:
            - NET_ADMIN
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Taipei
            - URL=${URL}
            - VALIDATION=http
        volumes:
            - ./config:/config
        ports:
            - 443:443
            - 80:80
        restart: unless-stopped
        depends_on:
            - backend
        networks:
            - net
    backend:
        image: zxc25077667/backend-exam:latest
        container_name: backend
        restart: unless-stopped
        networks:
            - net

networks:
    net: